### ISSUE TITLE
it is not keeping styles...

### ISSUE THREAD

**Issue by psellers89** [protobi/js-xlsx#12]
I don't understand, i installed using : npm install xlsx-style

my nodejs script is as simple as this :

var xlsx = require('xlsx-style');
var workbook = xlsx.readFile('template.xlsx');
xlsx.writeFile(workbook, 'out.xlsx');
console.log('Finished');

But all the styles disappeared. Am I missing something ?
Thanks

**Comment by VincentGuinaudeau** [comment]
yes, that something i run into a month ago.

I'm not sure if my solution is the best, but i workaround this by turing on the cellStyles attribute on the [parsing](https://github.com/protobi/js-xlsx#parsing-options).

```javascript
var xlsx = require('xlsx-style');
var workbook = xlsx.readFile('template.xlsx', {cellStyles: true});
xlsx.writeFile(workbook, 'out.xlsx');
console.log('Finished');
```

By doing this, all the style will by insertin the cell, instead of being list in another part of the workbook.

**Comment by pietersv** [comment]
Exactly, `{cellStyles: true}` is right.  That's inherited from the parent project.
