### ISSUE TITLE
"That command cannot be used on multiple selections"

### ISSUE THREAD

**Issue by jlhjr** [protobi/js-xlsx#26]
I get the below error message when I attempt to add a new worksheet to / copy cells from an Excel 2007 file generated in browser.  The issue does not seem to occur with the original SheetJS version, but then I lose the styling options that make this version so great!

![image](https://cloud.githubusercontent.com/assets/6693077/14265860/d5b36b4c-fa78-11e5-9ffe-acadd4ecf66a.png)

Here is an example: https://jsfiddle.net/jlhjr/0f8L9yfu/1/.  Am I doing something obviously wrong?

Note that a workaround is to do a "Save As" of the temporary file, which must cause Excel to fix the underlying issue.

Thank you!

**Comment by pietersv** [comment]
@jlhjr Wow, great catch.  The issue can be replicated in OSX Office 2011 and Office 365 for files generated in the browser and in Node, so this is a general issue and certainly not your doing.  

The issue seems to be resolvable by either commenting out  line 312 of `bits/67_wsxml.js` (and thus line 7845 of `xlsx.js`) or changing it from 
```js
tabSelected: opts.tabSelected === undefined ? '1' :  opts.tabSelected,
```
to 
```js
tabSelected: opts.tabSelected || undefined,
```

This of course will disable the new feature to set a particular tab as selected, but likely that's minor.

Comparing the file that this branch of js-xlsx generates to the one that Excel creates after opening and resaving, it's not clear to me yet why this change should matter, as both have 
```xml
<sheetView tabSelected="1" workbookViewId="0">

**Comment by jlhjr** [comment]
Thanks for the tip.  Commenting out that line certainly fixes the issue, but instead I decided to simply pass tabSelected = false in the workbook opts to avoid the problem entirely.

My initial sense is that for
```xml
<sheetView tabSelected="1">
```
to work, there must be a corresponding
```xml
<bookViews>
    <workbookView activeTab="0" />
</bookViews>
```
workbookView element in workbook.xml.  The <a href="https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.sheetview(v=office.15).aspx" target="_blank">OpenXML SDK</a> hints at why that might be:

><table>
  <tr>
    <td><p>tabSelected (Sheet Tab Selected)</p></td>
    <td>
        <p>Flag indicating whether this sheet is selected. When only 1 sheet is selected and active, this value should be in synch with the activeTab value. In case of a conflict, the Start Part setting wins and sets the active sheet tab.</p>
        <p>Multiple sheets can be selected, but only one sheet shall be active at one time.</p>
        <p>The possible values for this attribute are defined by the W3C XML Schema boolean datatype.</p>
    </td>
  </tr>
</table>

Just speculating here, but one of the things that resaving the file appears to do is add the necessary workbookView element missing from the browser (or Node) generated file.  The activeTab property of this element can specify the sheet to show on file open, but the default is to show the first tab.

So, in the short term, I might suggest that tabSelected default to '0' if undefined instead of '1' (i.e. the line you mention above).  To truly implement pre-selected tabs, it seems we need to also specify an active tab at the workbook level or allow it to default to the first tab.

**Comment by trcollinson** [comment]
My users were also having this problem with workbooks created by this version with the default tabSelected equal to true. They also noticed that when they would delete some sheets from a workbook, Excel would hang and quit unexpected. Setting tabSelected = false in the worksheet opts solved the problem.

**Comment by pietersv** [comment]
@jlhjr @trcollinson Thanks!  For now, have changed this to set `tabSelected="0"` unless otherwise specified.   Aim to add `< bookViews>` later.

* Made change to master (https://github.com/protobi/js-xlsx), ran `make` and pushed to GitHub
* Made change to beta branch (https://github.com/protobi/js-xlsx#beta), ran `make dist`, bumped version to `0.8.9` and published to npm (https://www.npmjs.com/package/xlsx-style)

Because tests don't yet work on Node 4+, pushed these without a comprehensive test run.
