### ISSUE TITLE
Width of the cell

### ISSUE THREAD

**Issue by GarikFF** [protobi/js-xlsx#54]
Hello.
Can I somehow set the width of the cell? I have a cell with a large content in my html-table, but when I create XLSX - it has default cell width.

**Comment by GarikFF** [comment]
I found this - http://stackoverflow.com/a/24466329, but is it right way?

**Comment by st-sloth** [comment]
Yup, for more info read https://github.com/protobi/js-xlsx#worksheet-object, section about `ws['!cols']`. In short, if you want to specify cell width in characters, use `wch`, if you want to specify cell width in pixels, use `wpx`. `wch` is preferable because this way you don't need to take the font typeface, size, etc. into account.
